// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsjuhnwzvhokxsxalzwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzanVobnd6dmhva3hzeGFsend4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDA2OTksImV4cCI6MjA1NTIxNjY5OX0.aCq3zDrgP3Wzrp-pAFsVxoIMOt5DOxyds71SwiSTUl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);